# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import os 
import sys
script_path = os.path.dirname(__file__)
sys.path.append(os.path.join(script_path))
import grpc
import warnings

import head_service_pb2 as head__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in head_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class HeadArkitStreamStub(object):
    """servo_json -- 示例 {"mouthUpperUpLeft":0.5,"mouthUpperUpRight":0.1...} 舵机参数

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetHeadState = channel.unary_unary(
                '/headarkit.HeadArkitStream/SetHeadState',
                request_serializer=head__service__pb2.HeadArkitMessage.SerializeToString,
                response_deserializer=head__service__pb2.Empty.FromString,
                _registered_method=True)
        self.GetHeadState = channel.unary_unary(
                '/headarkit.HeadArkitStream/GetHeadState',
                request_serializer=head__service__pb2.Empty.SerializeToString,
                response_deserializer=head__service__pb2.HeadArkitMessage.FromString,
                _registered_method=True)
        self.ReleaseControl = channel.unary_unary(
                '/headarkit.HeadArkitStream/ReleaseControl',
                request_serializer=head__service__pb2.Empty.SerializeToString,
                response_deserializer=head__service__pb2.Empty.FromString,
                _registered_method=True)


class HeadArkitStreamServicer(object):
    """servo_json -- 示例 {"mouthUpperUpLeft":0.5,"mouthUpperUpRight":0.1...} 舵机参数

    """

    def SetHeadState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeadState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeadArkitStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetHeadState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeadState,
                    request_deserializer=head__service__pb2.HeadArkitMessage.FromString,
                    response_serializer=head__service__pb2.Empty.SerializeToString,
            ),
            'GetHeadState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeadState,
                    request_deserializer=head__service__pb2.Empty.FromString,
                    response_serializer=head__service__pb2.HeadArkitMessage.SerializeToString,
            ),
            'ReleaseControl': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseControl,
                    request_deserializer=head__service__pb2.Empty.FromString,
                    response_serializer=head__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'headarkit.HeadArkitStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('headarkit.HeadArkitStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeadArkitStream(object):
    """servo_json -- 示例 {"mouthUpperUpLeft":0.5,"mouthUpperUpRight":0.1...} 舵机参数

    """

    @staticmethod
    def SetHeadState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/headarkit.HeadArkitStream/SetHeadState',
            head__service__pb2.HeadArkitMessage.SerializeToString,
            head__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHeadState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/headarkit.HeadArkitStream/GetHeadState',
            head__service__pb2.Empty.SerializeToString,
            head__service__pb2.HeadArkitMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/headarkit.HeadArkitStream/ReleaseControl',
            head__service__pb2.Empty.SerializeToString,
            head__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
