# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12head_service.proto\x12\theadarkit\"\x07\n\x05\x45mpty\"&\n\x10HeadArkitMessage\x12\x12\n\nservo_json\x18\x01 \x01(\t2\xc7\x01\n\x0fHeadArkitStream\x12=\n\x0cSetHeadState\x12\x1b.headarkit.HeadArkitMessage\x1a\x10.headarkit.Empty\x12=\n\x0cGetHeadState\x12\x10.headarkit.Empty\x1a\x1b.headarkit.HeadArkitMessage\x12\x36\n\x0eReleaseControl\x12\x10.headarkit.Empty\x1a\x10.headarkit.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'head_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_HEADARKITMESSAGE']._serialized_start=42
  _globals['_HEADARKITMESSAGE']._serialized_end=80
  _globals['_HEADARKITSTREAM']._serialized_start=83
  _globals['_HEADARKITSTREAM']._serialized_end=282
# @@protoc_insertion_point(module_scope)
